"""Add state_name and new measurement periods

Revision ID: 939311a0e4fc
Revises: df9a1c7e5dba
Create Date: 2025-10-21 00:09:57.312283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939311a0e4fc'
down_revision: Union[str, None] = 'df9a1c7e5dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nexus_rules', sa.Column('state_code', sa.String(length=2), nullable=False))
    op.add_column('nexus_rules', sa.Column('state_name', sa.String(length=50), nullable=True))
    op.drop_index('ix_nexus_rules_state', table_name='nexus_rules')
    op.create_index(op.f('ix_nexus_rules_state_code'), 'nexus_rules', ['state_code'], unique=False)
    op.drop_column('nexus_rules', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nexus_rules', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_nexus_rules_state_code'), table_name='nexus_rules')
    op.create_index('ix_nexus_rules_state', 'nexus_rules', ['state'], unique=False)
    op.drop_column('nexus_rules', 'state_name')
    op.drop_column('nexus_rules', 'state_code')
    # ### end Alembic commands ###
